# Generated by Django 3.1.2 on 2021-03-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
